language: java

jdk:
  - oraclejdk8

before_install:  
 - sudo apt-get update
 - sudo apt-get install apt-transport-https
 - sudo sh -c 'curl https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -'
 - sudo sh -c 'curl https://storage.googleapis.com/download.dartlang.org/linux/debian/dart_stable.list > /etc/apt/sources.list.d/dart_stable.list'
 - sudo apt-get update
 - sudo apt-get install dart
 
after_success:
  - export MAVEN_OPTS="-Xmx1024m"
  - mvn deploy -DskipTests=true

branches:
  only:
    - master
