name: Topophone
description: A sample web application
dependencies:
  browser: any
  route: any
  js: any
  polymer: ">=0.12.0 <0.13.0"
  core_elements: ">=0.1.0 <0.2.0"
  paper_elements: ">=0.1.0 <0.2.0"
transformers:
- polymer